AWSTemplateFormatVersion: "2010-09-09"
Description: UTNA food database stack

Parameters:
  UTNAFoodTableName:
    Type: String
  VisitedRestaurantTableName:
    Type: String

Resources:
  UTNAFoodTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Ref UTNAFoodTableName
      SSESpecification:
        SSEEnabled: false
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  VisitedRestaurantTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Ref VisitedRestaurantTableName
      SSESpecification:
        SSEEnabled: false
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  UTNAFoodTableName:
    Value: !Ref UTNAFoodTable
    Export:
      Name: !Sub "${AWS::StackName}-UTNAFoodTableName"
  VisitedRestaurantTableName:
    Value: !Ref VisitedRestaurantTable
    Export:
      Name: !Sub "${AWS::StackName}-VisitedRestaurantTableName"
